name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_TARGET: LiorPkg
  EDK2_REPO: https://github.com/tianocore/edk2.git
  EDK2_PATH: /home/runner/edk2

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: import EDK2
      uses: ./.github/templates/prepare_edk2.yml
      with:
        edk2_repo: ${{env.EDK2_REPO}}
        edk2_path: ${{env.EDK2_PATH}}

    - name: Install dependencies
      run: sudo apt install build-essential uuid-dev iasl git nasm  python-is-python3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DLOCAL_EDK2=${{env.EDK2_PATH}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target ${{env.BUILD_TARGET}}

  build-mac:
    runs-on: macos-12

    defaults:
      run:
        shell: zsh
    
    steps:
    - uses: actions/checkout@v3

    - name: import EDK2
      uses: ./.github/templates/prepare_edk2.yml
      with:
        edk2_repo: ${{env.EDK2_REPO}}
        edk2_path: ${{env.EDK2_PATH}}
      
    - name: install dependencies
      run: |
        xcode-select --install
        brew install mtoc nasm acpica qemu 
        export PATH=/usr/local/bin:$PATH

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DLOCAL_EDK2=${{env.EDK2_PATH}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target ${{env.BUILD_TARGET}}


      
