name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_TARGET: LiorPkg
  EDK2_REPO: https://github.com/tianocore/edk2.git
  EDK2_PATH: /home/runner/edk2

jobs:
  build-linux:
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - name: EDK2 cache
      id: cache-edk2
      uses: actions/cache@v3
      with:
        path: ${{env.EDK2_PATH}}
        key: edk2-repo
    - name: Clone EDK2
      if: steps.cache-edk2.outputs.cache-hit != 'true'
      run: |
        git clone ${{env.EDK2_REPO}} ${{env.EDK2_PATH}}
        cd ${{env.EDK2_PATH}}
        git submodule update --init
    - name: Fetch EDK2
      if: steps.cache-edk2.outputs.cache-hit == 'true'
      run: |
        cd ${{env.EDK2_REPO}}
        git fetch
        git submodule update

    - name: Install dependencies
      run: sudo apt install build-essential uuid-dev iasl git nasm  python-is-python3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DLOCAL_EDK2=${{env.EDK2_PATH}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target ${{env.BUILD_TARGET}}

  build-mac:
    runs-on: macos-12

    defaults:
      run:
        shell: zsh
    
    steps:
    - uses: actions/checkout@v3

    - name: EDK2 cache
      id: cache-edk2
      uses: actions/cache@v3
      with:
        path: ${{env.EDK2_PATH}}
        key: edk2-repo
    - name: Clone EDK2
      if: steps.cache-edk2.outputs.cache-hit != 'true'
      run: |
        git clone ${{env.EDK2_REPO}} ${{env.EDK2_PATH}}
        cd ${{env.EDK2_PATH}}
        git submodule update --init
    - name: Fetch EDK2
      if: steps.cache-edk2.outputs.cache-hit == 'true'
      run: |
        cd ${{env.EDK2_REPO}}
        git fetch
        git submodule update
      
    - name: install dependencies
      run: |
        xcode-select --install
        brew install mtoc nasm acpica qemu 
        export PATH=/usr/local/bin:$PATH

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DLOCAL_EDK2=${{env.EDK2_PATH}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target ${{env.BUILD_TARGET}}


      
