name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  BUILD_TARGET: LiorPkg
  EDK2_REPO: https://github.com/tianocore/edk2.git
  EDK2_PATH: /tmp/edk2

jobs:
###===================
# LINUX
###===================

  # check that build succeed on linux systems
  build-linux:
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    # import edk2 and cache it, for faster runs
    - name: EDK2 cache
      id: cache-edk2
      uses: actions/cache@v3
      with:
        path: ${{env.EDK2_PATH}}
        key: edk2-repo
    - name: Clone EDK2
      if: steps.cache-edk2.outputs.cache-hit != 'true'
      run: |
        git clone ${{env.EDK2_REPO}} ${{env.EDK2_PATH}}
        cd ${{env.EDK2_PATH}}
        git submodule update --init
    # make sure that edk2 in cache is up to date
    - name: Fetch EDK2
      if: steps.cache-edk2.outputs.cache-hit == 'true'
      run: |
        cd ${{env.EDK2_PATH}}
        git fetch
        git submodule update

    - name: Install dependencies
      run: sudo apt install build-essential uuid-dev iasl git nasm  python-is-python3

    - name: Configure CMake
      # sets LOCAL_EDK2 to cached repo path, to make configuration faster
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DLOCAL_EDK2=${{env.EDK2_PATH}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target ${{env.BUILD_TARGET}}

    - name: Save Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lior package binary
        path: ./**/OUTPUT/*.efi
        retention-days: 7
      

###===================
# MAC
###===================

  # check that build succeed on mac systems
  build-mac:
    runs-on: macos-12

    defaults:
      run:
        shell: bash
    
    steps:
    - uses: actions/checkout@v3

    # import edk2 and cache it, for faster runs
    - name: EDK2 cache
      id: cache-edk2
      uses: actions/cache@v3
      with:
        path: ${{env.EDK2_PATH}}
        key: edk2-repo
    - name: Clone EDK2
      if: steps.cache-edk2.outputs.cache-hit != 'true'
      run: |
        git clone ${{env.EDK2_REPO}} ${{env.EDK2_PATH}}
        cd ${{env.EDK2_PATH}}
        git submodule update --init
    # make sure that edk2 in cache is up to date
    - name: Fetch EDK2
      if: steps.cache-edk2.outputs.cache-hit == 'true'
      run: |
        cd ${{env.EDK2_PATH}}
        git fetch
        git submodule update
      
    - name: install dependencies
      run: |
        brew install mtoc nasm acpica qemu 
        export PATH=/usr/local/bin:$PATH

    - name: Configure CMake
      # sets LOCAL_EDK2 to cached repo path, to make configuration faster
      # sets EDK2_TAG to `edk2-stable202111` because there is a problem with the latest stable of edk2 (2022 05)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DLOCAL_EDK2=${{env.EDK2_PATH}} -DEDK2_TAG=edk2-stable202111

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target ${{env.BUILD_TARGET}}

    - name: Save Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lior package binary
        path: ./**/OUTPUT/*.efi
        retention-days: 7
      

###===================
# WINDOWS
###===================

  build-windows:
    runs-on: windows-2022

    defaults:
      run:
        shell: cmd
    
    env:
      EDK2_PATH: ${{runner.temp}}\edk2
    
    steps:
    - uses: actions/checkout@v3

    # import edk2 and cache it, for faster runs
    - name: EDK2 cache
      id: cache-edk2
      uses: actions/cache@v3
      with:
        path: ${{env.EDK2_PATH}}
        key: edk2-repo
    - name: Clone EDK2
      if: steps.cache-edk2.outputs.cache-hit != 'true'
      run: |
        git clone ${{env.EDK2_REPO}} ${{env.EDK2_PATH}}
        cd ${{env.EDK2_PATH}}
        git submodule update --init
    # make sure that edk2 in cache is up to date
    - name: Fetch EDK2
      if: steps.cache-edk2.outputs.cache-hit == 'true'
      run: |
        cd ${{env.EDK2_PATH}}
        git fetch
        git submodule update
      
    - name: copy pip requirements
      run: cp ${{env.EDK2_PATH}}\pip-requirements.txt .\requirements.txt

    - name: add pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies

    - name: Configure CMake
      # sets LOCAL_EDK2 to cached repo path, to make configuration faster
      run: cmake -B ${{github.workspace}}\build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DLOCAL_EDK2=${{env.EDK2_PATH}}

    - name: Build
      run: cmake --build ${{github.workspace}}\build --target ${{env.BUILD_TARGET}}

    - name: Save Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lior package binary
        path: ./**/OUTPUT/*.efi
        retention-days: 7

